INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (100, 'Comic Books');
 INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (200, 'Movies'), (3, 'Books');

INSERT INTO SUPPLIER (ID, NAME) VALUES (100, 'Panini Comics');
INSERT INTO SUPPLIER (ID, NAME) VALUES (200, 'Amazon');

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY, CREATED_AT) VALUES (100, 'Crise nas Infinitas terras', 100, 100, 10, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY, CREATED_AT) VALUES (200, 'Guerra Civil', 200, 200, 5, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY, CREATED_AT) VALUES (300, 'Harry Potter Box', 200, 200, 2, CURRENT_TIMESTAMP);
